name: RSpec Suite

on: [push]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build and test with rspec
        env:
          RUBYOPT: -W:no-deprecated
        run: bundle exec rspec spec
